version: '3.8'

services:
  aditya-hospital-admin:
    build: .
    container_name: aditya-hospital-admin
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - HOST=0.0.0.0
      - DOMAIN=adityahospitalnagaon.com
      - JWT_SECRET=aditya-hospital-nagaon-2025-super-secure-jwt-key
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./uploads:/app/uploads
    networks:
      - aditya-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    container_name: aditya-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - aditya-hospital-admin
    networks:
      - aditya-network

networks:
  aditya-network:
    driver: bridge

volumes:
  data:
  logs:
  uploads:

